delay:
  'https://github.com': 500 #Avoiding Github rate limit by delaying the request -> 500ms
ignore: 
  urls: # Array of url to ignore
  - https://swagger.io/
  - https://www.graylog.org/
  - https://riak.com/posts/technical/microservices-please-dont/
  - https://www.mdpi.com/2409-9287/6/4/81
  - https://www.http4k.org/


